<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Caculator regression" duration-ms="17101" started-at="2019-11-08T20:53:52 PST" finished-at="2019-11-08T20:54:09 PST">
    <groups>
    </groups>
    <test name="Metric Unit" duration-ms="17101" started-at="2019-11-08T20:53:52 PST" finished-at="2019-11-08T20:54:09 PST">
      <class name="modules.FindElement.CaculatorTest">
        <test-method status="PASS" signature="goToMetricUnit()[pri:0, instance:modules.FindElement.CaculatorTest@548e7350]" name="goToMetricUnit" is-config="true" duration-ms="12680" started-at="2019-11-08T20:53:52 PST" finished-at="2019-11-08T20:54:05 PST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goToMetricUnit -->
        <test-method status="FAIL" signature="CalulatorTest(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:modules.FindElement.CaculatorTest@548e7350]" name="CalulatorTest" duration-ms="4344" started-at="2019-11-08T20:54:05 PST" description="Validation" data-provider="testdata1" finished-at="2019-11-08T20:54:09 PST">
          <params>
            <param index="0">
              <value>
                <![CDATA[31]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[158]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[58]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[BMI = 23.6 kg/m2   (Normal)]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [BMI = 23.6 kg/m2   (Normal)] but found [BMI = 23.2 kg/m2   (Normal)]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [BMI = 23.6 kg/m2   (Normal)] but found [BMI = 23.2 kg/m2   (Normal)]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at modules.FindElement.CaculatorTest.CalulatorTest(CaculatorTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CalulatorTest -->
      </class> <!-- modules.FindElement.CaculatorTest -->
    </test> <!-- Metric Unit -->
  </suite> <!-- Caculator regression -->
</testng-results>
